export const BACKGROUNDS = [
  {id:'bg_black',name:'Void',price:0,css:'#000'},
  {id:'bg_navy',name:'Navy',price:250,css:'#0a0a2e'},
  {id:'bg_darkred',name:'Deep Red',price:250,css:'#1a0000'},
  {id:'bg_forest',name:'Forest',price:250,css:'#001a00'},
  {id:'bg_slate',name:'Slate',price:250,css:'#1a1a2e'},
  {id:'bg_charcoal',name:'Charcoal',price:250,css:'#1c1c1c'},
  {id:'bg_midnight',name:'Midnight',price:250,css:'#0d1b2a'},
  {id:'bg_purple',name:'Purple Night',price:250,css:'#1a0033'},
  {id:'bg_grid',name:'Grid',price:500,css:'grid'},
  {id:'bg_dots',name:'Dot Field',price:500,css:'dots'},
  {id:'bg_circuit',name:'Circuit',price:500,css:'circuit'},
  {id:'bg_neon',name:'Neon City',price:1500,css:'neon_city'},
  {id:'bg_galaxy',name:'Galaxy',price:1500,css:'galaxy'},
  {id:'bg_matrix',name:'Matrix',price:1500,css:'matrix'},
  {id:'bg_fire',name:'Hellfire',price:1500,css:'fire'},
  {id:'bg_redneon',name:'Red Neon',price:1500,css:'red_neon'},
  {id:'bg_eclipse',name:'Eclipse',price:1500,css:'eclipse'},
  {id:'bg_aurora',name:'Aurora',price:1500,css:'aurora'},
  {id:'bg_rain',name:'Rainfall',price:1500,css:'rain'},
  {id:'bg_vapor',name:'Vaporwave',price:1500,css:'vapor'},
];
