export const BALLS = [
  {id:'white',name:'Arctic White',color:'#ffffff',type:'basic',price:0},
  {id:'red',name:'Crimson',color:'#ff3333',type:'basic',price:500},
  {id:'blue',name:'Ocean',color:'#3399ff',type:'basic',price:500},
  {id:'green',name:'Lime',color:'#33ff77',type:'basic',price:500},
  {id:'orange',name:'Blaze',color:'#ff8833',type:'basic',price:500},
  {id:'purple',name:'Violet',color:'#aa44ff',type:'basic',price:500},
  {id:'pink',name:'Hot Pink',color:'#ff44cc',type:'basic',price:500},
  {id:'yellow',name:'Neon Yellow',color:'#ffee00',type:'basic',price:500},
  {id:'cyan',name:'Cyan',color:'#00ffee',type:'basic',price:500},
  {id:'gold',name:'Gold',color:'#ffd700',type:'basic',price:500},
  {id:'silver',name:'Chrome',color:'#c0c0d0',type:'basic',price:500},
  {id:'teal',name:'Teal',color:'#00b8a0',type:'basic',price:500},
  {id:'cat',name:'Cat',color:'#ffb347',type:'special',price:800,isCat:true},
  {id:'neon',name:'Neon Glow',color:'neon',type:'premium',price:1000},
  {id:'rainbow',name:'Rainbow',color:'rainbow',type:'premium',price:1000},
  {id:'galaxy',name:'Galaxy',color:'galaxy',type:'premium',price:1000},
  {id:'lava',name:'Lava',color:'lava',type:'premium',price:1000},
];
